version: '2'
services:
  scrapyd:
    image: sprasia/scrapyd:latest
    ports:
      - 6800:6800
    environment:
      TZ: Asia/Tokyo
    volumes:
      - scrapyd:/var/lib/scrapyd/

  spiderkeeper:
    build: .
    ports:
      - 5000:5000
    environment:
      SERVER: http://scrapyd:6800
      TZ: Asia/Tokyo
    volumes:
      - spiderkeeper:/db
    depends_on:
      - scrapyd

volumes:
  scrapyd:
  spiderkeeper:
